.on-release:
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release\\/.*$/"
      when: always

.build-kaniko:
  allow_failure: false
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context . --dockerfile $DOCKERFILE_PATH --destination $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG $DOCKER_BUILD_ARGS
  variables:
    DOCKERFILE_PATH: Dockerfile
    DOCKER_BUILD_ARGS: ""

.environment-django-ci:
  image: python:3.9.17-slim-bullseye
  services:
    - postgres:latest
  variables:
    ENV_FILE: .cicd/.env.ci
    POSTGRES_DB: nao_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  before_script:
    - apt-get update && apt-get install -y build-essential netcat
    - pip install --upgrade pip --cache-dir="$PIP_CACHE_DIR"
    - pip install --cache-dir="$PIP_CACHE_DIR" -r requirements.txt
    - set -a; source $ENV_FILE; set +a;
