# Generated by Django 4.1.2 on 2024-06-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Demande",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.basemodel",
                    ),
                ),
                ("duration", models.FloatField(blank=True, max_length=300)),
                ("deadline", models.DateField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True, max_length=500)),
                (
                    "type_video",
                    models.CharField(
                        choices=[("physique", "Physique"), ("digital", "Digital")],
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("arabe", "Arabe"),
                            ("français", "Français"),
                            ("anglais", "Anglais"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("homme", "Homme"), ("femme", "Femme")], max_length=50
                    ),
                ),
                ("comments", models.TextField(blank=True, max_length=500)),
            ],
            bases=("api.basemodel",),
        ),
    ]
