# Generated by Django 4.1.2 on 2024-06-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Demande",
            new_name="Demand",
        ),
    ]
