# Generated by Django 4.1.2 on 2024-06-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_demande_demand"),
    ]

    operations = [
        migrations.AddField(
            model_name="demand",
            name="taken",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
