# Generated by Django 4.1.2 on 2024-06-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_demand_taken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demand",
            name="deadline",
            field=models.DateField(blank=True),
        ),
    ]
