# Generated by Django 4.1.2 on 2024-06-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_demand_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Creator",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.basemodel",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("video_link", models.URLField(blank=True, null=True)),
                ("integration_date", models.DateField(blank=True, null=True)),
                ("videos_created", models.PositiveIntegerField(default=0)),
                ("rating", models.FloatField(default=0.0)),
            ],
            bases=("api.basemodel",),
        ),
    ]
