# Generated by Django 4.1.2 on 2024-06-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creator",
            name="video_link",
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_link", models.URLField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.creator"
                    ),
                ),
            ],
        ),
    ]
