# Generated by Django 4.1.2 on 2024-06-25 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0007_remove_creator_videos_created_demand_demandeur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demand",
            name="createur",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="createurs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
