# Generated by Django 4.1.2 on 2024-05-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_confirmationemailtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company_start_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="entity_start_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="unite",
        ),
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
    ]
