# Generated by Django 4.1.2 on 2024-06-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_remove_user_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_createur",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
